prerender:
    extends:
        file: docker-compose-common.yml
        service: prerender
    environment:
        ALLOWED_DOMAINS: citypantry.com
        PRERENDER_NUM_WORKERS: 2
        PRERENDER_NUM_ITERATIONS: 20
        VIRTUAL_HOST: prerender.tech.citypantry.com,prerender.citypantry.com
    links:
        - "redis:redis"
redis:
    extends:
        file: docker-compose-common.yml
        service: redis

